autodetect sample_rate and channels

diff --git a/pifon/fon/tools/vumeter b/pifon/fon/tools/vumeter
--- a/pifon/fon/tools/vumeter
+++ b/pifon/fon/tools/vumeter
@@ -45,6 +45,24 @@ if [ "$6" != "" ]; then
   ZERO_RANGE=$6
 fi
 
+# detect sample rate/channels?
+if [ "$SAMPLE_RATE" = "0" ]; then
+  if [ "$SYSTEM" = "Linux" ]; then
+    SAMPLE_RATE=`arecord --dump-hw-params -D $DEVICE 2>&1 | grep RATE: | sed -e 's/RATE: //g'`
+  else
+    echo "Can't autodetect sample_rate on $SYSTEM"
+    exit 1
+  fi
+fi
+if [ "$CHANNELS" = "0" ]; then
+  if [ "$SYSTEM" = "Linux" ]; then
+    CHANNELS=`arecord --dump-hw-params -D $DEVICE 2>&1 | grep CHANNELS: | sed -e 's/CHANNELS: //g'`
+  else
+    echo "Can't autodetect channels on $SYSTEM"
+    exit 1
+  fi
+fi
+
 # show options
 if [ "$DEBUG" != "" ]; then
   echo "SAMPLE_RATE=$SAMPLE_RATE INTERVAL=$INTERVAL CHANNELS=$CHANNELS RECORDER=$RECORDER DEVICE=$DEVICE ZERO_RANGE=$ZERO_RANGE" 2>&1
